[attempt] figuring out, why submitit launcher dies during instantiation
error:

Module for Miniconda3, version 4.10.3 loaded
[Hydra plugins scanner] : warnings from 'hydra_plugins.hyper_carp_s.hyper_carp_s'. Please report to plugin author.
/bigwork/nhwpruht/.conda/envs/cleanrl/lib/python3.10/site-packages/pkg_resources/__init__.py:121: DeprecationWarning: pkg_resources is deprecated as an API
  warnings.warn("pkg_resources is deprecated as an API", DeprecationWarning)
/bigwork/nhwpruht/.conda/envs/cleanrl/lib/python3.10/site-packages/pkg_resources/__init__.py:2870: DeprecationWarning: Deprecated call to `pkg_resources.declare_namespace('google')`.
Implementing implicit namespace packages (as specified in PEP 420) is preferred to `pkg_resources.declare_namespace`. See https://setuptools.pypa.io/en/latest/references/keywords.html#keyword-namespace-packages
  declare_namespace(pkg)
/bigwork/nhwpruht/.conda/envs/cleanrl/lib/python3.10/site-packages/pkg_resources/__init__.py:2870: DeprecationWarning: Deprecated call to `pkg_resources.declare_namespace('mpl_toolkits')`.
Implementing implicit namespace packages (as specified in PEP 420) is preferred to `pkg_resources.declare_namespace`. See https://setuptools.pypa.io/en/latest/references/keywords.html#keyword-namespace-packages
  declare_namespace(pkg)
Traceback (most recent call last):
  File "/bigwork/nhwpruht/aliced/fkit/main_mesa.py", line 354, in <module>
    main()
  File "/bigwork/nhwpruht/.conda/envs/cleanrl/lib/python3.10/site-packages/hydra/main.py", line 94, in decorated_main
    _run_hydra(
  File "/bigwork/nhwpruht/.conda/envs/cleanrl/lib/python3.10/site-packages/hydra/_internal/utils.py", line 394, in _run_hydra
    _run_app(
  File "/bigwork/nhwpruht/.conda/envs/cleanrl/lib/python3.10/site-packages/hydra/_internal/utils.py", line 465, in _run_app
    run_and_report(
  File "/bigwork/nhwpruht/.conda/envs/cleanrl/lib/python3.10/site-packages/hydra/_internal/utils.py", line 223, in run_and_report
    raise ex
  File "/bigwork/nhwpruht/.conda/envs/cleanrl/lib/python3.10/site-packages/hydra/_internal/utils.py", line 220, in run_and_report
    return func()
  File "/bigwork/nhwpruht/.conda/envs/cleanrl/lib/python3.10/site-packages/hydra/_internal/utils.py", line 466, in <lambda>
    lambda: hydra.multirun(
  File "/bigwork/nhwpruht/.conda/envs/cleanrl/lib/python3.10/site-packages/hydra/_internal/hydra.py", line 162, in multirun
    ret = sweeper.sweep(arguments=task_overrides)
  File "/bigwork/nhwpruht/aliced/hypersweeper/hydra_plugins/hypersweeper/hypersweeper.py", line 37, in sweep
    return self.sweeper.sweep(arguments)
  File "/bigwork/nhwpruht/aliced/hypersweeper/hydra_plugins/hypersweeper/hypersweeper_backend.py", line 165, in sweep
    incumbent = optimizer.run(verbose=True)
  File "/bigwork/nhwpruht/aliced/hypersweeper/hydra_plugins/hypersweeper/hypersweeper_sweeper.py", line 440, in run
    performances, costs = self.run_configs(
  File "/bigwork/nhwpruht/aliced/hypersweeper/hydra_plugins/hypersweeper/hypersweeper_sweeper.py", line 287, in run_configs
    res = self.launcher.launch(overrides, initial_job_idx=self.job_idx)
  File "/bigwork/nhwpruht/.conda/envs/cleanrl/lib/python3.10/site-packages/hydra_plugins/hydra_submitit_launcher/submitit_launcher.py", line 145, in launch
    jobs = executor.map_array(self, *zip(*job_params))
  File "/bigwork/nhwpruht/.conda/envs/cleanrl/lib/python3.10/site-packages/submitit/core/core.py", line 771, in map_array
    return self._internal_process_submissions(submissions)
  File "/bigwork/nhwpruht/.conda/envs/cleanrl/lib/python3.10/site-packages/submitit/auto/auto.py", line 218, in _internal_process_submissions
    return self._executor._internal_process_submissions(delayed_submissions)
  File "/bigwork/nhwpruht/.conda/envs/cleanrl/lib/python3.10/site-packages/submitit/slurm/slurm.py", line 326, in _internal_process_submissions
    d.dump(pickle_path)
  File "/bigwork/nhwpruht/.conda/envs/cleanrl/lib/python3.10/site-packages/submitit/core/utils.py", line 141, in dump
    cloudpickle_dump(self, filepath)
  File "/bigwork/nhwpruht/.conda/envs/cleanrl/lib/python3.10/site-packages/submitit/core/utils.py", line 233, in cloudpickle_dump
    cloudpickle.dump(obj, ofile, pickle.HIGHEST_PROTOCOL)
  File "/bigwork/nhwpruht/.conda/envs/cleanrl/lib/python3.10/site-packages/cloudpickle/cloudpickle_fast.py", line 57, in dump
    ).dump(obj)
  File "/bigwork/nhwpruht/.conda/envs/cleanrl/lib/python3.10/site-packages/cloudpickle/cloudpickle_fast.py", line 632, in dump
    return Pickler.dump(self, obj)
TypeError: cannot pickle '_Deterministic' object